---
name: Release to maven central

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decode secrets file
        run: |
          mkdir -p ./.gradle
          echo "${{ secrets.SECRETS_PROPERTIES }}" | base64 -d > ./.gradle/gradle.properties
          echo "${{ secrets.SECRING_ASC_GPG }}" | base64 -d > ./secring.asc.gpg
      - name: Build with Gradle
        run: ./gradlew --info -Prelease clean build
      - name: Upload archives with Gradle
        run: ./gradlew --info -Prelease uploadArchives
      - name: Close and release repository with Gradle
        run: ./gradlew --info -Prelease closeAndReleaseRepository
      - name: Decode secrets file
        run: |
          rm ./.gradle/gradle.properties
          rm ./secring.asc.gpg
