---
name: Release to maven central

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decode secrets file
        env:
          SECRETS_PROPERTIES: ${{ secrets.SECRETS_PROPERTIES }}
          SECRING_ASC_GPG: ${{ secrets.SECRING_ASC_GPG }}
        run: |
          echo "$SECRETS_PROPERTIES" | base64 -d >> ./gradle.properties
          echo "$SECRING_ASC_GPG" | base64 -d > ./secring.asc.gpg
      - name: Upload archives with Gradle
        run: ./gradlew --info -Prelease uploadArchives
      - name: Close and release repository with Gradle
        run: ./gradlew --info -Prelease closeAndReleaseRepository
      - name: Delete secrets
        run: |
          rm ./.gradle/gradle.properties
          rm ./secring.asc.gpg
